/** @file Generated by `generate-colors.cjs` script */

const colors = {
	'white': '#FFFFFF',
	'black': '#2B3037',
	'main': '#1A77F2',
	'gray-100': '#FBFBFB',
	'gray-300': '#E8E8EA',
	'gray-500': '#A5A3A9',
};

export default colors;
